---
version: "3.1"

services:
  photobooth-smtpd:
    image: vip-box/photobooth-smtpd
    ports:
      - 2525:25
    environment:
      - maildomain=mydomain.fr
      - smtp_user=user:password
      - rewrite_to=rewrite_email_to
